In [40]:
import numpy as np
import pandas as pd

In [83]:
df=pd.read_csv("MegaMart_sales.csv",index_col=[-2,-1])
df.head()

                                     Order ID  \
Category        Sub-Category
Office Supplies Labels        AZ-2011-1029887
Furniture       Furnishings    AZ-2011-107716
Technology      Accessories   AZ-2011-1087704
                Machines      AZ-2011-1372644
Office Supplies Art           AZ-2011-1362199

                                                            Product Name  \
Category        Sub-Category
Office Supplies Labels        Novimex Color Coded Labels, 5000 Label Set
Furniture       Furnishings               Deflect-O Door Stop, Erganomic
Technology      Accessories                Belkin Flash Drive, Bluetooth
                Machines                      Panasonic Printer, Durable
Office Supplies Art                            Sanford Pens, Fluorescent

                              Discount  Sales  Profit         Category
Category        Sub-Category
Office Supplies Labels             0.0     26       7  Office Supplies
Furniture       Furnishings        0.0     85      15        Furniture
Technology      Accessories        0.0    294     109       Technology
                Machines           0.0    800     168       Technology
Office Supplies Art                0.5     25     -11  Office Supplies

In [53]:
df=pd.read_csv("MegaMart_sales.csv",index_col=[-2,-1])
df_new=pd.read_csv("MegaMart_newsales.csv",index_col=[-2,-1])
df_new.head()

                                     Order ID  \
Category        Sub-Category
Office Supplies Binders       AZ-2011-1902971
Furniture       Bookcases     AZ-2011-1916360
Office Supplies Storage       AZ-2011-1916555
                Art           AZ-2011-1930058
Technology      Accessories   AZ-2011-1967754

                                                     Product Name  Discount  \
Category        Sub-Category
Office Supplies Binders       Wilson Jones Binding Machine, Clear       0.0
Furniture       Bookcases           Dania 3-Shelf Cabinet, Mobile       0.0
Office Supplies Storage               Eldon Folders, Single Width       0.4
                Art                   Sanford Markers, Easy-Erase       0.0
Technology      Accessories          Logitech Numeric Keypad, USB       0.0

                              Sales  Profit         Category
Category        Sub-Category
Office Supplies Binders         339     102  Office Supplies
Furniture       Bookcases       288      20        Furniture
Office Supplies Storage          61       7  Office Supplies
                Art              71       1  Office Supplies
Technology      Accessories      93      40       Technology

#### Combining two data frames
Question 1: Some of the orders are stored in another csv file named `megamart_new sales`. Read the csv file, store it in a data frame and add it to the `megamart_sales` data frame. Find the total sales value of the category 'Office Supplies'  after combining the dataframes

    a)7970
    b)6964
    c)7494
    d)6076

In [54]:
#your code here
df_new = pd.concat([df,df_new], axis=0)
df_new.count()

Order ID        68
Product Name    68
Discount        68
Sales           68
Profit          68
Category        68
dtype: int64

In [55]:
df.head(20)

                                     Order ID  \
Category        Sub-Category
Office Supplies Labels        AZ-2011-1029887
Furniture       Furnishings    AZ-2011-107716
Technology      Accessories   AZ-2011-1087704
                Machines      AZ-2011-1372644
Office Supplies Art           AZ-2011-1362199
Furniture       Furnishings   AZ-2011-1114253
Office Supplies Binders       AZ-2011-1116129
                Supplies      AZ-2011-1137571
Technology      Phones        AZ-2011-1174243
Office Supplies Labels         AZ-2011-122598
Furniture       Furnishings   AZ-2011-1229073
Office Supplies Art           AZ-2011-1240916
Furniture       Bookcases     AZ-2011-1253407
Technology      Accessories   AZ-2011-1087704
Office Supplies Storage       AZ-2011-1260928
                Binders       AZ-2011-1278696
                Supplies      AZ-2011-1279238
Furniture       Chairs         AZ-2011-130330
Office Supplies Storage       AZ-2011-1406494
                Appliances    AZ-2011-1315772

                                                            Product Name  \
Category        Sub-Category
Office Supplies Labels        Novimex Color Coded Labels, 5000 Label Set
Furniture       Furnishings               Deflect-O Door Stop, Erganomic
Technology      Accessories                Belkin Flash Drive, Bluetooth
                Machines                      Panasonic Printer, Durable
Office Supplies Art                            Sanford Pens, Fluorescent
Furniture       Furnishings                   Tenex Stacking Tray, Black
Office Supplies Binders                   Avery Binding Machine, Durable
                Supplies               Stiletto Letter Opener, Easy Grip
Technology      Phones                  Nokia Audio Dock, with Caller ID
Office Supplies Labels              Avery Removable Labels, Alphabetical
Furniture       Furnishings                   Deflect-O Door Stop, Black
Office Supplies Art                           Boston Canvas, Water Color
Furniture       Bookcases                 Safco Stackable Bookrack, Pine
Technology      Accessories                Belkin Flash Drive, Bluetooth
Office Supplies Storage                    Eldon File Cart, Single Width
                Binders                               Acco Binder, Clear
                Supplies                    Kleencut Scissors, Easy Grip
Furniture       Chairs                  Office Star Chairmat, Adjustable
Office Supplies Storage                     Fellowes Lockers, Industrial
                Appliances                       Breville Toaster, Black

                              Discount  Sales  Profit         Category
Category        Sub-Category
Office Supplies Labels             0.0     26       7  Office Supplies
Furniture       Furnishings        0.0     85      15        Furniture
Technology      Accessories        0.0    294     109       Technology
                Machines           0.0    800     168       Technology
Office Supplies Art                0.5     25     -11  Office Supplies
Furniture       Furnishings        0.0     76      11        Furniture
Office Supplies Binders            0.0    252      15  Office Supplies
                Supplies           0.0     90      17  Office Supplies
Technology      Phones             0.0   1334     200       Technology
Office Supplies Labels             0.0     32       6  Office Supplies
Furniture       Furnishings        0.0     88       3        Furniture
Office Supplies Art                0.0    284      43  Office Supplies
Furniture       Bookcases          0.1    541     156        Furniture
Technology      Accessories        0.0    294     109       Technology
Office Supplies Storage            0.1    576      51  Office Supplies
                Binders            0.0     44      14  Office Supplies
                Supplies           0.0     96      21  Office Supplies
Furniture       Chairs             0.1    307      99        Furniture
Office Supplies Storage            0.1    748     283  Office Supplies
                Appliances         0.0    152      44  Office Supplies

In [126]:
df=pd.read_csv("MegaMart_sales.csv",index_col=[-2,-1])
df_new=pd.read_csv("MegaMart_newsales.csv",index_col=[-2,-1])
df_new = pd.concat([df,df_new], axis=0)
df_new[["Sales"]].groupby("Category").sum()

                 Sales
Category
Furniture         2460
Office Supplies   7970
Technology        8588

In [113]:
d

NameError: name 'd' is not defined

#### Dropping duplicates
Question 2: There are some duplicate rows in the data frame. Drop these rows and calculate the total sales value of the category Office Supplies.

    a)7156
    b)6496
    c)6964
    d)6023

In [127]:
#your code here
df_new.drop_duplicates(inplace=True)

In [131]:
df_new = df_new.sort_values(by='Sales', ascending=False)
df_new.head()

                                     Order ID  \
Category        Sub-Category
Technology      Phones        AZ-2011-1410648
Office Supplies Appliances     AZ-2011-176674
Technology      Phones        AZ-2011-1174243
                Phones        AZ-2011-1322840
                Machines      AZ-2011-1372644

                                                  Product Name  Discount  \
Category        Sub-Category
Technology      Phones            Nokia Smart Phone, Full Size       0.0
Office Supplies Appliances               Hoover Microwave, Red       0.1
Technology      Phones        Nokia Audio Dock, with Caller ID       0.0
                Phones        Motorola Headset, with Caller ID       0.0
                Machines            Panasonic Printer, Durable       0.0

                              Sales  Profit         Category
Category        Sub-Category
Technology      Phones         1908     820       Technology
Office Supplies Appliances     1667     185  Office Supplies
Technology      Phones         1334     200       Technology
                Phones          957     316       Technology
                Machines        800     168       Technology

In [132]:
df_new[["Sales"]].groupby("Category").sum()

                 Sales
Category
Furniture         2460
Office Supplies   6964
Technology        7494

In [137]:
k =df_new[["Sales"]].groupby("Category").head(25)

In [138]:
k.head(25)

                              Sales
Category        Sub-Category
Technology      Phones         1908
Office Supplies Appliances     1667
Technology      Phones         1334
                Phones          957
                Machines        800
Office Supplies Storage         748
Technology      Accessories     666
                Phones          636
Furniture       Bookcases       630
Office Supplies Storage         576
Furniture       Bookcases       541
Office Supplies Art             510
Technology      Copiers         442
                Phones          364
Office Supplies Binders         339
Furniture       Chairs          307
Technology      Accessories     294
Furniture       Bookcases       288
Office Supplies Art             284
                Storage         255
                Binders         252
                Storage         241
                Art             193
                Supplies        176
Furniture       Chairs          164

#### Best category-sub category 
Question 3: Find the most profitable category and sub category combination based on the net profit.


    a)Furniture-Bookcases
    b)Office supplies-Appliances
    c)Office supplies-Storage
    d)Technology-Phones

In [61]:
df_new.head()

                                     Order ID  \
Category        Sub-Category
Office Supplies Labels        AZ-2011-1029887
Furniture       Furnishings    AZ-2011-107716
Technology      Accessories   AZ-2011-1087704
                Machines      AZ-2011-1372644
Office Supplies Art           AZ-2011-1362199

                                                            Product Name  \
Category        Sub-Category
Office Supplies Labels        Novimex Color Coded Labels, 5000 Label Set
Furniture       Furnishings               Deflect-O Door Stop, Erganomic
Technology      Accessories                Belkin Flash Drive, Bluetooth
                Machines                      Panasonic Printer, Durable
Office Supplies Art                            Sanford Pens, Fluorescent

                              Discount  Sales  Profit         Category
Category        Sub-Category
Office Supplies Labels             0.0     26       7  Office Supplies
Furniture       Furnishings        0.0     85      15        Furniture
Technology      Accessories        0.0    294     109       Technology
                Machines           0.0    800     168       Technology
Office Supplies Art                0.5     25     -11  Office Supplies

In [86]:
#your code here

df_new[["Profit"]].groupby(["Category","Sub-Category"]).sum()

                              Profit
Category        Sub-Category
Furniture       Bookcases        308
                Chairs           -49
                Furnishings       74
Office Supplies Appliances       229
                Art              275
                Binders          156
                Envelopes         35
                Fasteners         10
                Labels            30
                Paper             15
                Storage          192
                Supplies         103
Technology      Accessories      215
                Copiers            0
                Machines         168
                Phones          1618

#### Invalid order IDs
Question 4: How many invalid order IDs are there in the data frame. An order id is of the form AZ-2011-Y where Y represents a whole number. A Order ID is said to be valid only if Y consists of 7 digits. Find the number of valid order order IDs in the data frame.
    
    a)6
    b)7
    c)8
    d)9

In [102]:
#your code here
#len(df['Order ID'])>7
df_new[df_new['Order ID'].astype(str).map(len) != 15].count()

Order ID        7
Product Name    7
Discount        7
Sales           7
Profit          7
Category        7
dtype: int64

#### Occurence of furniture in top 25 sales
Question 5: Find the top 25 orders based on sales value and find the number of orders which belong to furniture category.

    a)2
    b)3
    c)4
    d)5

In [104]:
df=pd.read_csv("MegaMart_sales.csv")
df_new=pd.read_csv("MegaMart_newsales.csv")
df=pd.concat([df,df_new],axis=0,ignore_index=True) 

df.groupby(by='Category').Sales.sum()

Category
Furniture          2460
Office Supplies    7970
Technology         8588
Name: Sales, dtype: int64

In [105]:
df.drop_duplicates(subset=None,keep='first',inplace = True)
df.groupby(by='Category').Sales.sum()

Category
Furniture          2460
Office Supplies    6964
Technology         7494
Name: Sales, dtype: int64

In [106]:
df.groupby(by=['Category','Sub-Category']).Profit.sum()

Category         Sub-Category
Furniture        Bookcases        308
                 Chairs           -49
                 Furnishings       74
Office Supplies  Appliances       229
                 Art              275
                 Binders          156
                 Envelopes         35
                 Fasteners         10
                 Labels            30
                 Paper             15
                 Storage          192
                 Supplies         103
Technology       Accessories      215
                 Copiers            0
                 Machines         168
                 Phones          1618
Name: Profit, dtype: int64

In [110]:
df.groupby(by=['Category','Sub-Category']).Sales.head(20)

0       26
1       85
2      294
3      800
4       25
5       76
6      252
7       90
8     1334
9       32
10      88
11     284
12     541
14     576
15      44
16      96
17     307
18     748
19     152
20     957
21      87
22      33
23      28
24      82
26      38
27      13
30    1908
31     630
32      46
33     636
      ...
35      10
36      54
37      73
38     193
39     666
40      56
41     442
42     241
43     164
44      20
45      30
46     176
47      94
48     510
50      15
51      39
52     364
53      18
56     156
57      98
58    1667
59     339
60     288
61      61
62      71
63      93
64     132
65      97
66     136
67      52
Name: Sales, Length: 61, dtype: int64

#### And operation
Question 6: Among the orders with sales>250 and profit>50, find the product name of the fourth highest order based on sales value.

    a)Motorola Headset, with Caller ID
    b)Panasonic Printer, Durable	
    c)Hoover Microwave, Red	
    d)Fellowes Lockers, Industrial

In [139]:
#your code hereprofit>50
df_new[(df_new['Sales'] > 250) & (df_new['Profit'] > 50)]

                                     Order ID  \
Category        Sub-Category
Technology      Phones        AZ-2011-1410648
Office Supplies Appliances     AZ-2011-176674
Technology      Phones        AZ-2011-1174243
                Phones        AZ-2011-1322840
                Machines      AZ-2011-1372644
Office Supplies Storage       AZ-2011-1406494
Technology      Accessories   AZ-2011-1536006
                Phones        AZ-2011-1445262
Furniture       Bookcases      AZ-2011-144325
Office Supplies Storage       AZ-2011-1260928
Furniture       Bookcases     AZ-2011-1253407
Office Supplies Art           AZ-2011-1672552
Technology      Phones        AZ-2011-1722024
Office Supplies Binders       AZ-2011-1902971
Furniture       Chairs         AZ-2011-130330
Technology      Accessories   AZ-2011-1087704

                                                     Product Name  Discount  \
Category        Sub-Category
Technology      Phones               Nokia Smart Phone, Full Size       0.0
Office Supplies Appliances                  Hoover Microwave, Red       0.1
Technology      Phones           Nokia Audio Dock, with Caller ID       0.0
                Phones           Motorola Headset, with Caller ID       0.0
                Machines               Panasonic Printer, Durable       0.0
Office Supplies Storage              Fellowes Lockers, Industrial       0.1
Technology      Accessories       Logitech Keyboard, Programmable       0.0
                Phones                Apple Smart Phone, Cordless       0.0
Furniture       Bookcases           Bush Stackable Bookrack, Pine       0.0
Office Supplies Storage             Eldon File Cart, Single Width       0.1
Furniture       Bookcases          Safco Stackable Bookrack, Pine       0.1
Office Supplies Art               Binney & Smith Sketch Pad, Blue       0.0
Technology      Phones                     Cisco Audio Dock, VoIP       0.0
Office Supplies Binders       Wilson Jones Binding Machine, Clear       0.0
Furniture       Chairs           Office Star Chairmat, Adjustable       0.1
Technology      Accessories         Belkin Flash Drive, Bluetooth       0.0

                              Sales  Profit         Category
Category        Sub-Category
Technology      Phones         1908     820       Technology
Office Supplies Appliances     1667     185  Office Supplies
Technology      Phones         1334     200       Technology
                Phones          957     316       Technology
                Machines        800     168       Technology
Office Supplies Storage         748     283  Office Supplies
Technology      Accessories     666      66       Technology
                Phones          636     140       Technology
Furniture       Bookcases       630     132        Furniture
Office Supplies Storage         576      51  Office Supplies
Furniture       Bookcases       541     156        Furniture
Office Supplies Art             510     132  Office Supplies
Technology      Phones          364     142       Technology
Office Supplies Binders         339     102  Office Supplies
Furniture       Chairs          307      99        Furniture
Technology      Accessories     294     109       Technology

#### Column manipulation
Question 7: Remove the orders with negative profit by dropping the corresponding rows with negative `Profit`. Find the product that makes the lowest profit per Quantity in the Technology category.

    a) Nokia Audio Dock, with Caller ID
    b) Logitech Keyboard, Programmable
    c) Motorola Headset, with Caller ID
    d) Belkin Flash Drive, Bluetooth

In [143]:
#your code here

#df_new[df_new['Profit'] <= 0]
df_new.drop(df_new[df_new['Profit'] <= 0].index, inplace = True)

In [ ]:
df4=df[df.Profit>0]
df4=df4.loc[df4.Category=='Technology']

df4['Profit_per_qty']=df4['Profit']/df4['Quantity']

df4.sort_values(by='Profit_per_qty',ascending=True)